USE [master]
GO

/****** Object:  Database [MFG]    Script Date: 4/3/2021 2:29:36 PM ******/
CREATE DATABASE [MFG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MFG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MFG.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MFG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MFG_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MFG] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MFG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MFG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MFG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MFG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MFG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MFG] SET ARITHABORT OFF 
GO

ALTER DATABASE [MFG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MFG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MFG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MFG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MFG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MFG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MFG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MFG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MFG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MFG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MFG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MFG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MFG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MFG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MFG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MFG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MFG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MFG] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MFG] SET  MULTI_USER 
GO

ALTER DATABASE [MFG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MFG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MFG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MFG] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MFG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MFG] SET  READ_WRITE 
GO


