USE [MFG]
GO

/****** Object:  Table [dbo].[SYSCOMPANY]    Script Date: 4/3/2021 2:30:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SYSCOMPANY](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[RFC] [varchar](30) NOT NULL,
	[ADDRESS] [varchar](60) NOT NULL,
	[ADDRESS2] [varchar](60) NOT NULL,
	[ADDRESS3] [varchar](60) NOT NULL,
	[CITY] [varchar](60) NOT NULL,
	[STATE] [varchar](25) NOT NULL,
	[ZIP] [varchar](15) NOT NULL,
	[COUNTRY] [varchar](30) NOT NULL,
	[FAX] [varchar](30) NOT NULL,
	[TELEPHONE] [varchar](30) NOT NULL,
	[LOGO] [image] NULL,
	[SOURCE] [nvarchar](50) NOT NULL CONSTRAINT [DF_SYSCOMPANY_SOURCE]  DEFAULT (space((1))),
	[INICAT] [nvarchar](50) NOT NULL CONSTRAINT [DF_SYSCOMPANY_INICAT]  DEFAULT (space((1))),
	[SERUSER] [nvarchar](50) NOT NULL CONSTRAINT [DF_SYSCOMPANY_SERUSER]  DEFAULT (space((1))),
	[SERPASSWORD] [nvarchar](50) NOT NULL CONSTRAINT [DF_SYSCOMPANY_SERPASSWORD]  DEFAULT (space((1))),
	[INTSECURITY] [bit] NOT NULL CONSTRAINT [DF_SYSCOMPANY_INTSECURITY]  DEFAULT ((0)),
	[entbillunitprice] [bit] NOT NULL CONSTRAINT [DF_SYSCOMPANY_entbillunitprice]  DEFAULT ((1)),
	[web] [nvarchar](50) NOT NULL CONSTRAINT [DF_SYSCOMPANY_web]  DEFAULT (' '),
 CONSTRAINT [PK__SYSIMAGE__3214EC27748B4C66] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


